config/routes.rb
Ptucker::Application.routes.draw do
  resources :products

  get "categories/:id", to: "category#show"

  get "/about", to: "static#about"
  root "static#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, presence: true
  validates :name, length: { minimum: 3 }
  validates :description, presence: true
  validates :price, numericality: true

  has_one :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def show
    @id = params[:id]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category, :subcategory, :price, :dimensions, :condition)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about

  end

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/category/show.html.haml
%h2 HI HANK!
= @id

app/views/layouts/_navbar.html.haml
= link_to "Home", root_path
= link_to "Hollowware", "#"
= link_to "Flatware", "#"
= link_to "Small Gifts", "#"
= link_to "Boxes", "#"
= link_to "Jewelry", "#"
= link_to "About Us", about_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title Ptucker
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  = render partial: "layouts/navbar"
  = yield

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :subcategory
    = f.text_field :subcategory
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :dimensions
    = f.text_area :dimensions
  .field
    = f.label :condition
    = f.text_area :condition
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th Name
    %th Description
    %th Category
    %th Subcategory
    %th Price
    %th Dimensions
    %th Condition
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.description
      %td= product.category
      %td= product.subcategory
      %td= product.price
      %td= product.dimensions
      %td= product.condition
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Category:
  = @product.category
%p
  %b Subcategory:
  = @product.subcategory
%p
  %b Price:
  = @product.price
%p
  %b Dimensions:
  = @product.dimensions
%p
  %b Condition:
  = @product.condition

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path